<a href="https://colab.research.google.com/github/Imamahdysabilla/Machine-Learning/blob/main/2217051141_imam_ahdy_sabilla_A_pertemuan_ke_15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Library

In [23]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

## Load Data

In [24]:
df = pd.read_csv("https://raw.githubusercontent.com/rahmantaufik27/dataset/main/study/churn_bank_customer.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

## EDA

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [26]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

# Preprocessing

In [27]:
# split data menajdi data X dan Y (target/dependent variabel)
# data Exited digunakan sebagai data Y
Y = df.iloc[:,-1].values
# selain data Exited,RowNumber<CustomerId,Surname,digunakan sebagai data X
X = df.iloc[:,3:-1].values
print(Y)
print(X)

[1 0 1 ... 1 1 0]
[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]

In [28]:
# untuk data X,kita ubah terlebih dahulu data categorical (Geography,Gender) menjadi number
le = LabelEncoder()
X[:,2] = np.array(le.fit_transform(X[:,2]))
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder="passthrough")
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]

In [29]:
# split data otomatis/random menggunakan fungsi library tertentu
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [34]:
# scaling data
sc = StandardScaler()
X_train =  sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Modelling

In [35]:
# buat fungsi untuk pemodelan ANN
model_ann = tf.keras.Sequential([
    tf.keras.layers.Dense(units=6,activation="relu"),
    tf.keras.layers.Dense(units=6,activation="relu"),
    tf.keras.layers.Dense(units=1,activation="sigmoid")
])
# compile model ann
model_ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=['accuracy'])
# fitting data dengan model ann yang dibuat
model_ann.fit(X_train, Y_train, batch_size=32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6179 - accuracy: 0.6531
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4534 - accuracy: 0.8086
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4322 - accuracy: 0.8145
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4222 - accuracy: 0.8181
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4148 - accuracy: 0.8190
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4069 - accuracy: 0.8216
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3989 - accuracy: 0.8259
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3897 - accuracy: 0.8313
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3771 - accuracy: 0.8393
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3661 - accuracy: 0.8438
Epoch 11/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3602 - accuracy: 0.8475
Epoch 12/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3567 - accuracy: 0.8511
Epoch 13/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3535 - accuracy: 0.8514
Epoch 14/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3516 - accuracy: 0.8555
Epoch 15/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3502 - accuracy: 0.8535
Epoch 16/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3490 - accuracy: 0.8568
Epoch 17/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3478 - accuracy: 0.8571
Epoch 18/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3469 - accuracy: 0.8570
Epoch 19/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3457 - accuracy: 0.8585
Epoch 20/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3448 - accuracy: 0.8577
Epoch 21/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3440 - accuracy: 0.8595
Epoch 22/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3430 - accuracy: 0.8606
Epoch 23/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3419 - accuracy: 0.8611
Epoch 24/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3416 - accuracy: 0.8614
Epoch 25/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3411 - accuracy: 0.8599
Epoch 26/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3402 - accuracy: 0.8608
Epoch 27/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3397 - accuracy: 0.8620
Epoch 28/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3392 - accuracy: 0.8634
Epoch 29/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3387 - accuracy: 0.8622
Epoch 30/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3382 - accuracy: 0.8634
Epoch 31/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3379 - accuracy: 0.8635
Epoch 32/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3375 - accuracy: 0.8616
Epoch 33/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3369 - accuracy: 0.8646
Epoch 34/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3364 - accuracy: 0.8633
Epoch 35/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3362 - accuracy: 0.8639
Epoch 36/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3358 - accuracy: 0.8635
Epoch 37/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3356 - accuracy: 0.8649
Epoch 38/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3351 - accuracy: 0.8644
Epoch 39/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3347 - accuracy: 0.8635
Epoch 40/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3348 - accuracy: 0.8649
Epoch 41/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3348 - accuracy: 0.8634
Epoch 42/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3343 - accuracy: 0.8634
Epoch 43/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3337 - accuracy: 0.8631
Epoch 44/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3338 - accuracy: 0.8648
Epoch 45/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3339 - accuracy: 0.8643
Epoch 46/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3335 - accuracy: 0.8624
Epoch 47/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3329 - accuracy: 0.8640
Epoch 48/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3328 - accuracy: 0.8627
Epoch 49/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3323 - accuracy: 0.8627
Epoch 50/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3329 - accuracy: 0.8644
Epoch 51/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3329 - accuracy: 0.8634
Epoch 52/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3325 - accuracy: 0.8629
Epoch 53/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3323 - accuracy: 0.8644
Epoch 54/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3324 - accuracy: 0.8635
Epoch 55/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3324 - accuracy: 0.8639
Epoch 56/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3318 - accuracy: 0.8644
Epoch 57/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3321 - accuracy: 0.8635
Epoch 58/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3319 - accuracy: 0.8645
Epoch 59/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3319 - accuracy: 0.8640
Epoch 60/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3317 - accuracy: 0.8650
Epoch 61/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3319 - accuracy: 0.8640
Epoch 62/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3315 - accuracy: 0.8652
Epoch 63/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3315 - accuracy: 0.8655
Epoch 64/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3314 - accuracy: 0.8651
Epoch 65/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3315 - accuracy: 0.8639
Epoch 66/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3314 - accuracy: 0.8655
Epoch 67/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3313 - accuracy: 0.8646
Epoch 68/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3316 - accuracy: 0.8658
Epoch 69/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3309 - accuracy: 0.8636
Epoch 70/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3310 - accuracy: 0.8656
Epoch 71/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3312 - accuracy: 0.8637
Epoch 72/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3308 - accuracy: 0.8650
Epoch 73/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3307 - accuracy: 0.8655
Epoch 74/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3308 - accuracy: 0.8652
Epoch 75/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3306 - accuracy: 0.8655
Epoch 76/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3305 - accuracy: 0.8658
Epoch 77/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3305 - accuracy: 0.8654
Epoch 78/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3304 - accuracy: 0.8643
Epoch 79/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3303 - accuracy: 0.8656
Epoch 80/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3306 - accuracy: 0.8646
Epoch 81/100
250/250 [==============================] - 2s 6ms/step - loss: 0.3304 - accuracy: 0.8650
Epoch 82/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3305 - accuracy: 0.8652
Epoch 83/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3299 - accuracy: 0.8674
Epoch 84/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3303 - accuracy: 0.8664
Epoch 85/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3300 - accuracy: 0.8664
Epoch 86/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3301 - accuracy: 0.8651
Epoch 87/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3301 - accuracy: 0.8666
Epoch 88/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3299 - accuracy: 0.8654
Epoch 89/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3299 - accuracy: 0.8655
Epoch 90/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3302 - accuracy: 0.8649
Epoch 91/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3300 - accuracy: 0.8643
Epoch 92/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3300 - accuracy: 0.8648
Epoch 93/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3298 - accuracy: 0.8651
Epoch 94/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3296 - accuracy: 0.8658
Epoch 95/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3296 - accuracy: 0.8656
Epoch 96/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3296 - accuracy: 0.8641
Epoch 97/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3305 - accuracy: 0.8651
Epoch 98/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3295 - accuracy: 0.8662
Epoch 99/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3296 - accuracy: 0.8652
Epoch 100/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3299 - accuracy: 0.8658

# Evaluation

In [32]:
model_ann.evaluate(X_test, Y_test, batch_size=8)

250/250 [==============================] - 1s 1ms/step - loss: 0.7005 - accuracy: 0.4885

[0.7004820108413696, 0.4884999990463257]

In [33]:
# coba prediksi satu data
print(model_ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1,50000]]))>0.5)

1/1 [==============================] - 0s 122ms/step
[[ True]]